export const siteUrl = "https://amirlan.dev";

export const profile = {
  name: "Amirlan Kalmukhan",
  givenName: "Amirlan",
  familyName: "Kalmukhan",
  aliases: [
    "amirlan",
    "amirlan kalmukhan",
    "amirlankalm",
    "amirlannk",
  ],
  title: "Co-founder at Geko",
  email: "amirlan@geko.sh",
  location: {
    city: "Astana",
    country: "Kazakhstan",
    countryCode: "KZ",
  },
  description:
    "Amirlan Kalmukhan is a 15-year-old co-founder at Geko, building expert-authored training data and real-time audio reinforcement-learning environments for human-like speech models.",
  shortDescription:
    "Co-founder at Geko, building training data and RL environments for human-like voice.",
  company: {
    name: "Geko",
    url: "https://geko.sh",
    accelerator: "Training data and RL environments for human-like voice",
  },
  keywords: [
    "Amirlan",
    "Amirlan Kalmukhan",
    "amirlan kalmukhan",
    "amirlankalm",
    "Geko",
    "voice AI",
    "speech AI",
    "training data",
    "reinforcement learning environments",
    "audio reinforcement learning",
    "human-like voice",
    "speech models",
    "co-founder",
    "linguistics",
    "phonetics",
    "Speko",
    "YC S26",
    "robotics",
    "research",
    "Astana",
    "Kazakhstan",
  ],
  knowsAbout: [
    "voice AI",
    "speech training data",
    "reinforcement learning environments",
    "real-time audio reinforcement learning",
    "human-like speech",
    "linguistics",
    "phonetics",
    "robotics",
  ],
  sameAs: [
    "https://x.com/amirlankalm",
    "https://github.com/amirlankalm",
    "https://www.linkedin.com/in/amirlan-kalmukhan-a02ab4366/",
    "https://instagram.com/amirlannk",
  ],
} as const;
